name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Deploy
      run: bash deploy.sh
      env:
          PRIVKEY: ${{ secrets.PRIVKEY }}
          SERVER_PASS: ${{ secrets.SERVER_PASS }}
      
